### ISSUE TITLE
It also seems to be like adding a basic editor into the program might be useful.

### ISSUE THREAD

**Issue by BadDragor** [BadDragor/TextSeparatorSpellChecker#10]
One way to do it would be to alow user to change the text in the dataGridView. The program could remember which line it is and just replace that line in the txt file with that line from the dataGridView when the user leaves the cell.

The problem is that a txt file doesn't hold formating. For that reason it was meant for the user to click on the cell (the text is loaded into the clipBoard automatically, I think) and then click ctrl+F on the GDoc of the story and then ctrl+V. That way, the very source can be edited.

**Comment by sweetaibelle** [comment]
I was largely thinking of having a separate window with a text control that the file gets loaded into, and adding basic notepad-like functionality to that window. Potentially, this could even be the main window, making the grammar checking results (and statistics) a secondary window.

**Comment by BadDragor** [comment]
I've solved this with a new tab. Let me know if you still want to stick with extra windows.

**Comment by BadDragor** [comment]
@sweetaibelle The second tab is an editor with RichTextBox. I think it supports colors, bold and italics. It doesn't save, but the user can copy paste it to the source.
