### ISSUE TITLE
SpellChecking feature

### ISSUE THREAD

**Issue by BadDragor** [BadDragor/TextSeparatorSpellChecker#11]
As far as I know,  the text in the dataGridView cell can't be formatted easily. This might be a problem to implement.

**Comment by sweetaibelle** [comment]
Not sure on the ui side. The actual spellchecking side, there are definitely places where we could get dictionaries to use, like here:
https://github.com/dwyl/english-words

**Comment by BadDragor** [comment]
We could use this on the second tab with the whole text. The words that aren't in a dictionary could be bolded, for instance.

One challenge I see is synchronization with the first tab. One solution would be to just save and re-initialize on every tab change.

**Comment by BadDragor** [comment]
@sweetaibelle Both first and second tabs can be edited by the user. The user can than copy paste it to the source text.
