### ISSUE TITLE
give us more statistics

### ISSUE THREAD

**Issue by BadDragor** [BadDragor/TextSeparatorSpellChecker#12]
This feature might be best implemented in another tab.

The best first step for this feature would be brainstorming on which statistics should be implemented.

**Comment by sweetaibelle** [comment]
Obvious things we could add include:
Number of characters.
Number of words. (Flashfic mode that warns you if it's over a word limit?)
Number of sentences.
Number of paragraphs. (Maybe flag if the paragraphs are too long?)

A list of the top x words in the story could be fun. Maybe filter out some of the really commonly used words.
Vocabulary level of story? (Okay, I don't know how to implement that. I know it can be done.)

**Comment by sweetaibelle** [comment]
Depending on how many stats we have, we might be able to just put a status bar at the bottom of the window, and show statistics there...

**Comment by BadDragor** [comment]
I don't think your solution is future-proof. I think a seperate tab for statistics is better. That way we aren't limited with space. Also, I've already added a tab for this. Let me know if I failed to change your mind with the current design solution.

**Comment by BadDragor** [comment]
@sweetaibelle Solved. We now have paragraph count, sentences count (maybe), word count and letter count.
