### ISSUE TITLE
Word count

### ISSUE THREAD

**Issue by BadDragor** [BadDragor/TextSeparatorSpellChecker#6]
The program knows how to count characters but not words. A feature to count words could be added.

**Comment by sweetaibelle** [comment]
Could probably be combined with the statistics issue, really.

**Comment by BadDragor** [comment]
I agree. The statistics might grow so perhaps we could form a new tab on the designer just for statistics.

This code you found looks really good.
Imports System.Text.RegularExpressions

Module Module1
    Sub Main()
        ' Count words in this string.
        Dim value As String = "To be or not to be, that is the question."
        Dim count1 As Integer = CountWords(value)

        ' Count words again.
        value = "Mary had a little lamb."
        Dim count2 As Integer = CountWords(value)

        ' Display counts.
        Console.WriteLine(count1)
        Console.WriteLine(count2)
    End Sub

    ''' <summary>
    ''' Use regular expression to count words.
    ''' </summary>
    Public Function CountWords(ByVal value As String) As Integer
        ' Count matches.
        Dim collection As MatchCollection = Regex.Matches(value, "\S+")
        Return collection.Count
    End Function
End Module

I didn't know there's a class and a function for it already in .net

**Comment by sweetaibelle** [comment]
Honestly, there are undoubtedly other things we could do with regular expressions, too. 

Before I found that, I was thinking in terms of running some sort of split function on the string with the story in it, since most languages tend to have one, then checking the number of elements in the array.

**Comment by BadDragor** [comment]
Yes, I was thinking something along those lines as well. Good thing you found the code, else we'd make it complicated and bad.

I've added paragraph count to the statistics tab. We can throw loads more.

**Comment by BadDragor** [comment]
@sweetaibelle Solved.
