### ISSUE TITLE
The default path could be the executable directory path

### ISSUE THREAD

**Issue by BadDragor** [BadDragor/TextSeparatorSpellChecker#9]

**Comment by sweetaibelle** [comment]
Potential ideas were the executable path, the Documents folder, and the windows temp directory. We could potentially test if the path is writable before defaulting to it.

**Comment by BadDragor** [comment]
Best to just keep everything in the same place, I think. That way the program instantly works even if you copy it to somewhere else.

**Comment by sweetaibelle** [comment]
Seems reasonable.

**Comment by BadDragor** [comment]
Solved.
The path actually gets saved, but on the first run, the default path will be the executable directory path.
